### ISSUE TITLE
Time values horribly broken on Safari

### ISSUE THREAD

**Issue by gm-stack** [timvideos/streaming-system#102]
Safari 8.0.2, Mac OS X 10.10.1

Date parsing code appears to be doing something strange and returns a time value from the distant past.

![screen shot 2015-01-16 at 1 02 26 pm](https://cloud.githubusercontent.com/assets/2130440/5769422/30425570-9d80-11e4-98de-4f614c3e5f90.png)

**Comment by joeladdison** [comment]
Fixed in 00d6f6967
